os: osx
language: objective-c
osx_image: xcode9.3
xcode_project: HelloWorld/HelloWorld.xcodeproj # path to your xcodeproj folder
xcode_scheme: HelloWorld
script: xctool -project HelloWorld/HelloWorld.xcodeproj -scheme HelloWorld run-tests -test-sdk iphonesimulator11.3