os:
 - osx
 - linux
language:
 - android
 - objective-c
osx_image: xcode9.3
before_install:
 - brew update
 - brew cask install fastlane
 - brew install yarn
script:
 - cd $TRAVIS_BUILD_DIR/packages/mobile/
 - yarn install
 - cd $TRAVIS_BUILD_DIR
 - fastlane ios test