// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import "HWTodo.h"
#import <Foundation/Foundation.h>
@class HWTodoList;


@interface HWTodoList : NSObject

+ (nullable HWTodoList *)createWithPath:(nonnull NSString *)path;

- (nonnull NSArray<HWTodo *> *)getTodos;

- (int32_t)addTodo:(nonnull NSString *)label;

- (BOOL)updateTodoCompleted:(int32_t)id
                  completed:(int32_t)completed;

- (BOOL)deleteTodo:(int32_t)id;

@end
